# Generated by Django 5.2.4 on 2025-08-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(help_text='One ingredient per line')),
                ('instructions', models.TextField()),
                ('category', models.CharField(choices=[('appetizer', 'Appetizer'), ('main', 'Main Course'), ('dessert', 'Dessert'), ('drink', 'Drink'), ('side', 'Side')], default='main', max_length=20)),
                ('prep_time_minutes', models.PositiveIntegerField()),
                ('cook_time_minutes', models.PositiveIntegerField()),
                ('servings', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='RestoBan_re_slug_9be92e_idx')],
            },
        ),
    ]
